#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
  
hi() { 
  tput bold; tput setaf 5
  cat<<-'EOF'

   -=-        “A saint is not someone who never sins, 
(\  _  /)      but one who sins less and less frequently."
( \( )/ )      ― St. Bernard of Clairvaux            
(       )
 `>   <'
 /     \  hjw
 `-._.-'
         
	EOF
  tput bold; tput setaf 241
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

if [ -z "$txtSin21" ]; then
  txtSin21="$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"
  txtSin21="$txtSin21" bash --init-file "${BASH_SOURCE[0]}" -i
else
  alias ..='cd ..'
  alias ...='cd ../../../'

  alias bye="gp; tmux detach"
  alias egrep='egrep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias gp="git add *;git commit -am save;git push;git status"
  alias grep='grep --color=auto'
  alias h="history"
  alias keys="lisp keys.lisp "
  alias hello="git pull"
  alias ls="ls -G"
  alias repl="rlwrap sbcl --noinform " 
  alias tmux="tmux -f $txtSin21/etc/dottmux "
  alias vi="vim -u $txtSin21/etc/dotvimrc "
  alias vims="vim +PluginInstall +qall"         

  mkdir -p $txtSin21/docs

  htmls() {  
    (cd $txtSin21/src
    for i in *.lisp
    do
       doc $i
    done
    )
  }
  doc() {  
      (cat $txtSin21/README.md | gawk '
            BEGIN { FS="\n"; RS="" }
                  { print  $0 "\n"; exit}' |
       gawk '{print "; " $0}
             END {print("\n\n;\n\n")}'  
      cat $1 | gawk '
      BEGIN {FS="\n";RS=""}
      NR==1 { print("\n\n"); next}
            {print $0 ""}'
      ) > $txtSin21/docs/$1
      (cd $txtSin21/docs; docco  -o . $1) 
      cp $txtSin21/etc/docco.css $txtSin21/docs
  }
  lisp()  {
    f=$1
    shift
    sbcl --noinform --script $f  $* 2> >( gawk ' {print} /^5:/ {exit}' ) 
  }
  
  here() { cd $1; basename `pwd`; }
  
  PROMPT_COMMAND='echo -ne "🧠 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
  hi
fi
